#! /bin/sh
# assumes luatool.py is in your path
LUA_TOOL=luatool/luatool/luatool.py
for i in src/*.lua; do
	i_base=$(basename $i)
	#print $i_base
	$LUA_TOOL --port /dev/ttyUSB0 --src $i --dest $i_base --baud 9600
done